JoberChipFrappuccino/joberchip-fe

src/components/Space/ActionBlockFormBase.module.scss
src/components/Space/ActionBlockFormBase.tsx

Drawer 내에서 블록 타입을 변경 할 수 있도록 로직을 수정했습니다.
https://github.com/JoberChipFrappuccino/joberchip-fe/assets/73880776/daf40056-b8cb-4ab2-bb61-f648e7064537

Drawer block type 이동 되도록 변경

---

src/components/Forms/ImageBlockForm.module.scss
src/components/Forms/ImageBlockForm.tsx
src/components/Forms/LinkBlockForm.module.scss
src/components/Forms/LinkBlockForm.tsx
src/components/Forms/VideoBlockForm.module.scss
src/components/Forms/VideoBlockForm.tsx
src/components/Space/ActionBlockFormBase.tsx
src/components/Space/SwitchActionBlock.tsx

1. 링크, 사진, 동영상 폼 작성 페이지 레이아웃 작업
2. 사진, 동영상 파일 불러오기 후 미리보기 이미지 표시
1. 사진, 동영상의 경우 미리보기 이미지 생성후 미리보기 이미지를 다시 클릭하면 데이터 초기화
1. 링크 폼 스크린샷
2. 사진 폼 스크린샷
3. 동영상 폼 스크린샷

Feature/link video image froms layout #13

---

src/components/Layouts/Layout.tsx
src/components/Menus/Header.tsx
src/components/Menus/SpaceListBar.tsx
tsconfig.json

feat:breadcrumb ui완료 #19

---

src/components/Space/Profile.tsx
src/components/Tree/TreeDrawer.tsx

Profile 케밥 메뉴에 저장위치 변경 Button 생성했습니다
클릭시 오른쪽에 Tree관련 Drawer 펼쳐짐

feat: '저장위치 변경' Button생성

---

src/components/Space/Profile.module.scss

중간 결과물 배포 전 profile CSS를 수정했습니다.

profile CSS 수정

---

mocks/production/space.json
src/.eslintrc.json
src/components/ActionBar/BlockActionBar.tsx
src/components/Blocks/ViewerBlockBase.module.scss
src/components/Blocks/ViewerBlockBase.tsx
src/components/Modal/ConfirmModal.module.scss
src/components/Modal/ConfirmModal.tsx
src/components/Space/Profile.module.scss
src/components/Space/Profile.tsx
src/components/Space/SpaceViewer.tsx
src/components/Tree/TreeDrawer.tsx
src/hooks/debounce.ts

- comfirm 모달 추가
- mock API 오타 수정
- useDebounce 추가
- confirm 모달 추가
- useDebounce hook 추가
/hooks/debounce.tsx 참고해주세용!
```js
useDebounce(grid.layouts.lg, 2000, (nextLayout) => {
// console.log('layout changed', nextLayout)
})
```

스페이스 기능 정리 및 수정 (요약 참고)

---

mocks/development/space.json
src/components/Blocks/PageBlock.tsx
src/components/Forms/PageBlockForm.tsx
src/components/Menus/Header.tsx
src/components/SwitchCase/DrawerCreateForm.tsx
src/components/SwitchCase/DrawerEditForm.tsx
src/components/Tree/TreeLayout.tsx
src/models/space.ts

Page수정 Drawer 기존 데이터 표시되게 UI 수정

Page수정 Drawer 기존 데이터 표시되게 UI 수정

---

server/render/render.tsx
server/routes/auth.ts
src/api/api.ts
src/api/space.ts
src/api/user.ts
src/components/ActionBar/SpaceActionBar.module.scss
src/components/Blocks/ImageBlock.module.scss
src/components/Home/GroupSpace.tsx
src/components/Home/UserProfile.tsx
src/components/Layouts/SpaceLayout.tsx
src/components/Space/Profile.tsx
src/constants/index.ts
src/constants/queryKey.ts
src/models/space.ts
src/pages/Home/index.tsx
src/pages/SignIn/index.tsx
src/store/user.ts
src/types/space.d.ts

렌딩 페이지 space 추가, 조회 API를 연동했습니다.
- space 추가
`src/components/Home/UserProfile.tsx`를 참고해주세요.
```js
const handleOnClickCreateSpace = () => {
createSpaceAPI()
.then(({ message }) => {
alert(message)
queryClient.refetchQueries([SPACE_LIST])
})
.catch(({ message }) => {
alert(message)
})
```
- space 리스트 조회
`src/pages/Home/index.tsx`를 참고해주세요.
```js
const { data } = useQuery([SPACE_LIST], () => getSpaceListAPI(), {
staleTime: 1000 * 60 * 60
})
```

렌딩 페이지 space 추가, 조회 API 연동

---

mocks/development/space.json
mocks/production/space.json
src/components/Forms/PageBlockForm.module.scss
src/components/Forms/PageBlockForm.tsx
src/components/Menus/Header.tsx
src/components/Menus/SideNavBar.tsx
src/components/SwitchCase/DrawerCreateForm.tsx
src/components/SwitchCase/DrawerEditForm.tsx
src/components/Tree/TreeDrawer.module.scss
src/components/Tree/TreeDrawer.tsx
src/components/Tree/TreeLayout.tsx

edit상태에서 Tree컴포넌트 파일 draggable기능 optional화
create할 때는 파일위치변경(drag)불가, 이외 수정중일때는 가능하게 수정

feat: edit상태에서 Tree컴포넌트 파일 draggable기능 optional화

---

src/App.tsx
src/components/Blocks/ViewerBlockBase.module.scss
src/components/Layouts/Layout.tsx
src/components/Menus/Header.tsx
src/components/SharePage/DropDownMenu.tsx
src/components/SharePage/Profile.tsx
src/components/SharePage/ProfileForm.module.scss
src/components/SharePage/ProfileForm.tsx
src/components/SharePage/SharePageBlocksViewer.module.scss
src/components/Space/UserProfile.tsx
src/hooks/debounce.ts
src/pages/SignIn/SignIn.module.scss
src/pages/SignIn/index.tsx
src/pages/Space/index.tsx
src/store/user.ts

프로파일 수정 기능, debouncing 을 적용했습니다.
랜딩페이지 로그인 오류를 수정했습니다.

프로파일 수정 기능, debouncing 적용

---

package-lock.json
package.json
src/components/Forms/GoogleMapBlockForm.module.scss
src/components/Forms/GoogleMapBlockForm.tsx
src/components/SwitchCase/DrawerCreateForm.tsx
src/components/SwitchCase/DrawerEditForm.tsx
src/models/space.ts

구글맵지도 검색 기능 완료, 블록 추가 삭제 수정 진행중, 백앤드 api 대로 models/sapace.ts interface에 추가
env 파일에 구글 맵 키 입력해야함

구글맵지도 검색 기능 완료

---

src/App.tsx
src/components/Blocks/ViewerBlockBase.module.scss
src/components/Blocks/ViewerBlockBase.tsx
src/components/Forms/TemplateBlockCreateForm.module.scss
src/components/Modal/TemplatePreviewModal.module.scss
src/components/SharePage/Profile.tsx
src/components/SharePage/TemplateSearchBox.module.scss
src/components/Tree/TreeDrawer.module.scss
src/components/Ui/Button.module.scss
src/components/Ui/Button.tsx

일부 블럭 스타일 수정

---

mocks/production/space.json
src/components/Blocks/TextBlock.tsx
src/components/Forms/TextBlockForm.tsx
src/models/space.ts
src/pages/Space/index.tsx
src/pages/TempSharePage/index.tsx
src/store/sharePage.ts
src/store/user.ts
src/utils/api.ts

- backend API property가 수정되어서 일부 type을 변경했습니다.
- blocks CRUD작업에 필요한 util함수를 추가했습니다.

getNextYOfLastBlock util 함수 추가 및 back sharePage api 타입 수정

---

src/components/Forms/GoogleMapBlockForm.module.scss
src/components/Forms/GoogleMapBlockForm.tsx

지도 추가하기 추가, lat, lng등 위치 출력하도록 변경, TODO가 작업해야하는 영역

---

src/api/blocks.ts
src/components/Forms/ImageBlockForm.tsx
src/components/Forms/LinkBlockForm.tsx
src/components/Forms/VideoBlockForm.tsx

Link 블록 추가 기능 API 작업

---

src/api/blocks.ts
src/components/Blocks/GoogleMapBlock.tsx
src/components/Forms/GoogleMapBlockForm.tsx
src/models/space.ts

구글 지도 블럭추가, 블럭수정 api 추가
이후 구글 블럭 수정해야함

구글 지도 블럭추가, 블럭수정 api 추가

---

src/api/page.ts
src/components/Forms/PageBlockForm.tsx
src/components/Layouts/SpaceLayout.tsx
src/components/Layouts/TempSharePageLayout.tsx

feat: Page 생성 API 연동 완료

---

src/api/tree.ts
src/components/Forms/PageBlockForm.tsx
src/components/Tree/TreeDrawer.tsx
src/components/Tree/TreeLayout.tsx
src/constants/queryKeyConstant.ts
src/hooks/tree.ts

Page생성시 body에 실리는 parentId 추가완료

feat: Page추가 API body에 ParentId 추가완료

---

server/routes/space.ts
server/utils/getSpaceById.ts
src/api/api.ts
src/api/blocks.ts
src/api/space.ts
src/components/Blocks/GoogleMapBlock.module.scss
src/components/Blocks/GoogleMapBlock.tsx
src/components/Menus/BreadCrumb.tsx
src/components/SharePage/Profile.tsx
src/components/SharePage/ProfileForm.tsx
src/components/SharePage/SharePageBlocksViewer.tsx
src/constants/blockSizeConstant.ts
src/constants/queryKeyConstant.ts
src/constants/sharePageConstant.ts
src/hooks/debounce.ts
src/models/space.ts
src/pages/SharePage/index.tsx
src/pages/TempSharePage/index.tsx
src/store/sharePage.ts
src/types/space.d.ts

dashboard API, 블럭위치 리사이즈 API 연결

dashboard API, 블럭위치 리사이즈 API 연결

---

src/components/Forms/PageBlockForm.tsx

feat:PageBlock 수정 API 완료

---

src/api/api.ts
src/api/blocks.ts
src/components/Forms/ImageBlockForm.tsx
src/components/Forms/LinkBlockForm.tsx
src/components/Forms/VideoBlockForm.tsx
src/components/SwitchCase/DrawerEditForm.tsx
src/models/space.ts

feat : 링크, 이미지, 비디오 블록 추가 기능 API 작업 #98

---

src/api/delete.ts
src/components/Blocks/ViewerBlockBase.tsx

feat : 블럭 삭제 임시

---

server/routes/auth.ts
src/components/Blocks/ViewerBlockBase.tsx
src/components/Forms/PageBlockForm.tsx
src/components/Tree/TreeLayout.tsx
src/store/sharePage.ts

fix : page errror
